---
:path: "/Users/philippeperret/Library/Mobile Documents/com~apple~CloudDocs/Musique/Analyses/SCHUBERT-Trio100/schub_trio100/images/_Chantier/CG1"
:config:
  page: a4
  mesure:
  systeme: '1'
  proximity: '5'
  barres: true
  stems: true
  tune: Eb
  time: 3/4
  auto_update_after_change: false
  staves_vspace:
  staves:
    keys:
    - F
  disposition: left_right
  note_tune_fixed: false
:used_at: 1669037381
