---
:path: "/Users/philippeperret/Library/Mobile Documents/com~apple~CloudDocs/Musique/Analyses/SCHUBERT-Trio100/schub_trio100/images/_Chantier/CRG1"
:config:
  page: a4
  mesure:
  systeme: mono
  proximity:
  barres: true
  stems: true
  tune: Eb
  time: 3/4
  auto_update_after_change: false
  staves_vspace:
  staves: {}
  disposition: left_right
  note_tune_fixed: false
:used_at: 1669033872
