# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '2.7.3'

gem 'bundler', '2.1.4'
gem 'erb'
gem 'yaml'
gem 'pretty_inspect'
gem 'clir'
gem 'selenium-webdriver'
